# -*- coding: utf-8 -*-
"""xml_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bB0zRtGaTtLsv-CsQvMqMFPgSbtoxdfu
"""

import pandas as pd
import xml.etree.ElementTree as ET
import os

def parse_annotation(ann_dir, img_dir, labels=[], x_ratio =1, y_ratio = 1):
    all_imgs = []
    seen_labels = {}
    
    for ann in sorted(os.listdir(ann_dir)[:1200]):
        img = {'object':[]}

        tree = ET.parse(ann_dir + ann)
        
        for elem in tree.iter():
            if 'filename' in elem.tag:
                img['filename'] = img_dir + elem.text
            if 'width' in elem.tag:
                img['width'] = int(elem.text)
            if 'height' in elem.tag:
                img['height'] = int(elem.text)
            if 'object' in elem.tag or 'part' in elem.tag:
                obj = {}
                
                for attr in list(elem):
                    if 'name' in attr.tag:
                        obj['name'] = attr.text

                        if obj['name'] in seen_labels:
                            seen_labels[obj['name']] += 1
                        else:
                            seen_labels[obj['name']] = 1
                        
                        if len(labels) > 0 and obj['name'] not in labels:
                            break
                        else:
                            img['object'] += [obj]
                    if 'bndbox' in attr.tag:
                        for dim in list(attr):
                            if 'xmin' in dim.tag:
                                obj['xmin'] = int(round(float(dim.text))*x_ratio)
                            if 'ymin'  in dim.tag:
                                obj['ymin'] = int(round(float(dim.text))*y_ratio)
                            if 'xmax' in dim.tag:
                                obj['xmax'] = int(round(float(dim.text))*x_ratio)
                            if 'ymax' in dim.tag:
                                obj['ymax'] = int(round(float(dim.text))*y_ratio)

        if len(img['object']) > 0:
            all_imgs += [img]
                        
    return all_imgs, seen_labels

LABELS = ['Mongoloid', 'Negroid', 'Caucasian'] # array containing labels. Can be more than one.
train_image_folder = 'content/drive/My Drive/Colab Notebooks/train_images/'
train_annot_folder = 'content/drive/My Drive/Colab Notebooks/images_xml/'

train_imgs_A, seen_train_labels_A = parse_annotation(train_annot_folder, train_image_folder, labels=LABELS,)

seen_train_labels_A

labels_ids = {"Mongoloid":"Mongoloid","Negroid": "Negroid", "Caucasian":"Caucasian"}

f = open ('anno1.csv', 'w+')
for img_number in range(0,len(train_imgs_A)):
    image = train_imgs_A[img_number]
    im_name = f"/{image['filename']}"
    objects = image['object']
    # print (im_name)
#     line = im_name
    for objs in objects:
        xmin = objs['xmin']
        ymin = objs['ymin']
        xmax = objs['xmax']
        ymax = objs['ymax']
        c_id = labels_ids[objs['name']]
#         print (xmin, ymin, xmax, ymax, c_id)
        line = im_name+','+str(xmin)+',' +str(ymin)+',' +str(xmax)+','+str(ymax)+','+ str(c_id) +'\n'
        f.write (line)

  #  print (line)
    
f.close()

def parse_annotation(ann_dir, img_dir, labels=[], x_ratio =1, y_ratio = 1):
    all_imgs = []
    seen_labels = {}
    
    for ann in sorted(os.listdir(ann_dir)[1200:1290]):
        img = {'object':[]}

        tree = ET.parse(ann_dir + ann)
        
        for elem in tree.iter():
            if 'filename' in elem.tag:
                img['filename'] = img_dir + elem.text
            if 'width' in elem.tag:
                img['width'] = int(elem.text)
            if 'height' in elem.tag:
                img['height'] = int(elem.text)
            if 'object' in elem.tag or 'part' in elem.tag:
                obj = {}
                
                for attr in list(elem):
                    if 'name' in attr.tag:
                        obj['name'] = attr.text

                        if obj['name'] in seen_labels:
                            seen_labels[obj['name']] += 1
                        else:
                            seen_labels[obj['name']] = 1
                        
                        if len(labels) > 0 and obj['name'] not in labels:
                            break
                        else:
                            img['object'] += [obj]
                    if 'bndbox' in attr.tag:
                        for dim in list(attr):
                            if 'xmin' in dim.tag:
                                obj['xmin'] = int(round(float(dim.text))*x_ratio)
                            if 'ymin'  in dim.tag:
                                obj['ymin'] = int(round(float(dim.text))*y_ratio)
                            if 'xmax' in dim.tag:
                                obj['xmax'] = int(round(float(dim.text))*x_ratio)
                            if 'ymax' in dim.tag:
                                obj['ymax'] = int(round(float(dim.text))*y_ratio)

        if len(img['object']) > 0:
            all_imgs += [img]
                        
    return all_imgs, seen_labels

LABELS = ['Mongoloid', 'Negroid', 'Caucasian'] # array containing labels. Can be more than one.
train_image_folder = 'content/drive/My Drive/Colab Notebooks/train_images/'
train_annot_folder = 'content/drive/My Drive/Colab Notebooks/images_xml/'

train_imgs_B, seen_train_labels_B = parse_annotation(train_annot_folder, train_image_folder, labels=LABELS,)

seen_train_labels_B

f = open ('anno2.csv', 'w+')
for img_number in range(0,len(train_imgs_B)):
    image = train_imgs_B[img_number]
    im_name = f"/{image['filename']}"
    objects = image['object']
    # print (im_name)
#     line = im_name
    for objs in objects:
        xmin = objs['xmin']
        ymin = objs['ymin']
        xmax = objs['xmax']
        ymax = objs['ymax']
        c_id = labels_ids[objs['name']]
#         print (xmin, ymin, xmax, ymax, c_id)
        line = im_name+','+str(xmin)+',' +str(ymin)+',' +str(xmax)+','+str(ymax)+','+ str(c_id) +'\n'
        f.write (line)

  #  print (line)
    
f.close()

def parse_annotation(ann_dir, img_dir, labels=[], x_ratio =1, y_ratio = 1):
    all_imgs = []
    seen_labels = {}
    
    for ann in sorted(os.listdir(ann_dir)[1294:]):
        img = {'object':[]}

        tree = ET.parse(ann_dir + ann)
        
        for elem in tree.iter():
            if 'filename' in elem.tag:
                img['filename'] = img_dir + elem.text
            if 'width' in elem.tag:
                img['width'] = int(elem.text)
            if 'height' in elem.tag:
                img['height'] = int(elem.text)
            if 'object' in elem.tag or 'part' in elem.tag:
                obj = {}
                
                for attr in list(elem):
                    if 'name' in attr.tag:
                        obj['name'] = attr.text

                        if obj['name'] in seen_labels:
                            seen_labels[obj['name']] += 1
                        else:
                            seen_labels[obj['name']] = 1
                        
                        if len(labels) > 0 and obj['name'] not in labels:
                            break
                        else:
                            img['object'] += [obj]
                    if 'bndbox' in attr.tag:
                        for dim in list(attr):
                            if 'xmin' in dim.tag:
                                obj['xmin'] = int(round(float(dim.text))*x_ratio)
                            if 'ymin'  in dim.tag:
                                obj['ymin'] = int(round(float(dim.text))*y_ratio)
                            if 'xmax' in dim.tag:
                                obj['xmax'] = int(round(float(dim.text))*x_ratio)
                            if 'ymax' in dim.tag:
                                obj['ymax'] = int(round(float(dim.text))*y_ratio)

        if len(img['object']) > 0:
            all_imgs += [img]
                        
    return all_imgs, seen_labels

LABELS = ['Mongoloid', 'Negroid', 'Caucasian'] # array containing labels. Can be more than one.
train_image_folder = 'content/drive/My Drive/Colab Notebooks/train_images/'
train_annot_folder = 'content/drive/My Drive/Colab Notebooks/images_xml/'

train_imgs_C, seen_train_labels_C = parse_annotation(train_annot_folder, train_image_folder, labels=LABELS,)

seen_train_labels_C

f = open ('anno3.csv', 'w+')
for img_number in range(0,len(train_imgs_C)):
    image = train_imgs_C[img_number]
    im_name = f"/{image['filename']}"
    objects = image['object']
    # print (im_name)
#     line = im_name
    for objs in objects:
        xmin = objs['xmin']
        ymin = objs['ymin']
        xmax = objs['xmax']
        ymax = objs['ymax']
        c_id = labels_ids[objs['name']]
#         print (xmin, ymin, xmax, ymax, c_id)
        line = im_name+','+str(xmin)+',' +str(ymin)+',' +str(xmax)+','+str(ymax)+','+ str(c_id) +'\n'
        f.write (line)

  #  print (line)
    
f.close()